AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for SnsNotifierLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  SnsNotifierLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/SnsNotifierLambda/
      Handler: SnsNotifierLambda::SnsNotifierLambda.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        SnsNotifierLambda:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find ou t more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SnsNotifierLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for SnsNotifierLambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SnsNotifierLambdaFunction:
    Description: "SnsNotifierLambda Lambda Function ARN"
    Value: !GetAtt SnsNotifierLambdaFunction.Arn
  SnsNotifierLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for SnsNotifierLambda function"
    Value: !GetAtt SnsNotifierLambdaFunctionRole.Arn
